[package]
name = "sim_functions_for_ahnlich"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
